### ISSUE TITLE
Lack of error handling during file deletion in 'gpt-engineer/main.py'

### ISSUE THREAD

**Issue by Madhav-MKNC** [AntonOsika/gpt-engineer#225]
**Description**
The code currently deletes files and subdirectories using the shutil.rmtree function when the delete_existing flag is set to True. However, it does not handle any potential errors that may occur during the deletion process. This can result in unexpected behavior or unhandled exceptions, leaving the application in an inconsistent state.

Here's a suggested approach to handle errors during deletion:

```[python]
try:
    shutil.rmtree(memory_path, ignore_errors=True)
    shutil.rmtree(workspace_path, ignore_errors=True)
except Exception as e:
    # Handle the exception
    logging.error("An error occurred while deleting files: %s", str(e))
```

**Comment by patillacode** [comment]
Hi @Madhav-MKNC 

Thanks for your suggestion, although for cases like this I would suggest you create a PR rather than paste the code in a comment.

Would you be interested on creating a PR with these changes? if so, here is the [contributing guidelines](https://github.com/AntonOsika/gpt-engineer/blob/main/.github/CONTRIBUTING.md) file

**Comment by Madhav-MKNC** [comment]
Hey @patillacode 
Yes sure, I would like to submit a PR for sure.

**Comment by AntonOsika** [comment]
If you get an error, don't use the flag. Easy as that.
