### ISSUE TITLE
Permission denied (publickey). cloning

### ISSUE THREAD

**Issue by ligarius** [AntonOsika/gpt-engineer#266]
$ git clone git@github.com:AntonOsika/gpt-engineer.git
Cloning into 'gpt-engineer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by patillacode** [comment]
It says on the message:

```
Please make sure you have the correct access rights
and the repository exists.
```

You are not properly cloning the repo, try with the http instead of the ssh link
```
$ git clone https://github.com/AntonOsika/gpt-engineer.git
```

**Comment by codergautam** [comment]
Then why is this on the Readme command on the readme?! 

Making a pr

**Comment by patillacode** [comment]
Hi @codergautam 

The command is NOT broken. Allow me to elaborate a bit more.

We (in a wrong way, seems like) assumed that only developers would follow the developers instructions.

If you are a developer working with GitHub you should be aware of properly using the ssh link with your credentials ([ssh-keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)) properly set up, that is why I referred OP to the "not so developer link"

That is probably my mistake, I should have redirected him to `pip install gpt-engineer` but since he wanted to clone the repo and not just install it, I mentioned the http link.
