### ISSUE TITLE
Python project as asset. 

### ISSUE THREAD

**Issue by singersbalm** [AntonOsika/gpt-engineer#443]
I was thinking if it would be possible to give an existing project in python to gpt with an explanation what this project does and the question if it could build the same app in a language like c.

**Comment by noxiouscardiumdimidium** [comment]
with about the same success rate as normal based on the quality of prompt and the overall workflow of changes step type and refining the prompt, giving feedback at run-end (then running use_feedback if its working. the other day i was having problems with 2_word step types with an underscore.. haven't checked today since i pulled again. if and when it works its a good tool for that, always ad a note to the last question, reminding it that  its "transposing"/"transliterating" from one format to another ) ... ive had really good results with quick tests of prompt templates like this

```
###<(interpreted as a full stop) HEADER MESSAGE/TITLE BAR:
# <(like a \n\n indent into a sub menu/value array)BRIEF DESCRIPTION:

### 
# 1. BULLET 
# 2. POINTS
# 3. OF 
# 4. FEATURES

### CURRENT REVISION:
``` FILETYPE

CODEBLOCK BODY

```
### FULL DESCRIPTION:
#

### EXECUTE INSTRUCTIONS:
# 1. LIST
# 2. OF
# 3. ADDITIONAL
# 4. INSTRUCTIONS
! RETURN ALL REVISED OUTPUT AS `FILE TYPE`!
```

**Comment by noxiouscardiumdimidium** [comment]
the required backticks keep messing everything up xP
