### ISSUE TITLE
command not found: gpt-engineer

### ISSUE THREAD

**Issue by H31md411** [AntonOsika/gpt-engineer#491]
I did everything exactly like in the instructions but when i run:
gpt-engineer --help

it throws: ❯ gpt-engineer --help
zsh: command not found: gpt-engineer

What could i have done wrong?

**Comment by joseasilverio** [comment]
Same here. I'm trying to understand why it's not working either.

**Comment by azrv** [comment]
Please provide an output of `pip install -e .` while you are in repo directory

**Comment by pinakdave** [comment]
Same issue here. I used "make install && source venv/bin/activate" command

**Comment by georgewoodall82** [comment]
looks like your using zsh, try typing in bash and running the command again (this might not work if your using a mac)

**Comment by nordquist** [comment]
+1

**Comment by yelin-zdk** [comment]
It seems like you are trying to execute a Python script but facing some issues because the directory where the script is installed is not in your system's PATH.

The PATH is an environment variable on Unix-like operating systems, DOS, OS/2, and Microsoft Windows, specifying a set of directories where executable programs are located.

The message is recommending that you add the directory to your PATH or use --no-warn-script-location to suppress the warning.

If you're using a Unix-like operating system such as Linux or macOS, you can add the directory to your PATH with the following command:

bash

**export PATH=$PATH:/XXX(your path)**

You can add this line to your .bashrc or .zshrc file to make this change permanent (This file is usually located in your home directory).

If you're using Windows, you would follow these steps:

    Search for "Environment Variables" in your computer's start menu.
    Select "Edit the system environment variables".
    In the System Properties window that appears, click on the "Environment Variables" button.
    In the Environment Variables window, scroll down in the "System variables" section to find "Path" and click on it.
    Click the "Edit" button.
    In the Edit Environment Variable window, click "New" and then paste in the directory.

Please replace these instructions with the appropriate ones for your shell and operating system if they differ. After updating the PATH variable, you will need to restart your terminal or command prompt session to ensure the changes take effect.

**Comment by isosatya** [comment]
This didn´t help me and I am still stuck :(

**Comment by isosatya** [comment]
Here is the definite solution:

https://bobbyhadz.com/blog/python-the-script-is-installed-in-which-is-not-on-path#unix-the-script-pip-is-installed-in-usrlocalbin-which-is-not-on-path
