### ISSUE TITLE
Using Anthropic's Claude API

### ISSUE THREAD

**Issue by alissonryan** [AntonOsika/gpt-engineer#516]
Could you include the use of Claude from Anthropic?

Here is the API documentation:
https://docs.anthropic.com/claude/reference/getting-started-with-the-api

**Comment by shahiryar** [comment]
I think Anthropic don't have a python library to enable effective integration with this project. However, I think, in order to use Claude one will have to create a module that could abstract api calls as well as prompt deign.

**Comment by alissonryan** [comment]
they have a python library as per the link below. Would it be possible with this information?

https://docs.anthropic.com/claude/reference/client-libraries
https://github.com/anthropics/anthropic-sdk-python

**Comment by shahiryar** [comment]
Yeah, I think this is sufficient a starting point to add support for this model.
I am currently, reading this repo, perhaps I could fork and try adding the feature to use claud here.

**Comment by alissonryan** [comment]
OK thank you. I'm really enjoying Claude and have been using it for some no-code projects of mine.

**Comment by yanhuixie** [comment]
I have just found this repo but I'm not sure if it will help. @shahiryar 
https://github.com/jtsang4/claude-to-chatgpt

**Comment by st1vms** [comment]
Hello, I recently made an unofficial api for claude2, in order to automate free accounts, having auto session and user agent gathering using a Firefox login and selenium. Along with timezone. 
My unofficial version of the API does currently work like a charm, especially if using a VPN on allowed countries, it supports chat creation/deletion/retrieval and messages with attachments (with all the supported file types). It also let you handle a MessageRateLimit exception that provides you with the amount of seconds to sleep before next rateReset. 

Come have a try! Leave a :star: if you can : )

https://github.com/st1vms/unofficial-claude2-api

**Comment by AntonOsika** [comment]
We have support for this now, see docs!

**Comment by btvd** [comment]
@AntonOsika Hey, Anton! Can you spell some light on how to configure gpt-engineer to work with Anthropic API? I did not find anything in docs about it... Very thank you for help!

**Comment by viborc** [comment]
Hey @btvd, we currently have a PR with this (https://github.com/gpt-engineer-org/gpt-engineer/pull/1057), and I think we'll soon have it implemented.

**Comment by parinaysethtecholution** [comment]
Can someone guide me how to configure for  gpt-engineer to work with Anthropic

**Comment by viborc** [comment]
> Can someone guide me how to configure for gpt-engineer to work with Anthropic

I'll check this for you, @parinaysethtecholution!

**Comment by johndpope** [comment]
make it easier to configure claude like put instructions on the readme - 
I search the docs - get lost - search this repo for claude - get lost - etc
too hard to configure - it only mentions gpt api key in docs from what I can see.
