### ISSUE TITLE
Directions are very confusing

### ISSUE THREAD

**Issue by clearsitedesigns** [AntonOsika/gpt-engineer#535]
I'm on a mac and got the pip running fine, but the help is not even helpful. Whats the extension the prompt file needs to be? Can we at least use our AI to make our documentation better? That was a criticism.  Your video shows you using different file names  via vim that are not the same name of the file?

**Comment by piyushnags** [comment]
Disclaimer: I'm not an official maintainer, but I've just gotten started with this project

I agree. The documentation is a little confusing and could use some more details. There have also been changes to file names. I'm leaving this info here so anyone having trouble getting started can use this until the documentation is updated:

The prompt file should be saved without an extension (you can do this in vim by just running 'vi prompt'). If you try to save it as prompt.txt, the program will throw an assertion error telling you that the prompt should be saved in a file called "prompt".

With regard to the video, I'm not entirely sure about what you're referring to. I'm guessing you are talking about the command 'python main.py snake' when the prompt file is called main_prompt (I'm assuming the demo video is old since prompts should now be saved in a file called prompt) . Note that the command line argument is the name of the directory containing the prompt file, not the name of the prompt file. Also, at the time of writing this, you don't use the command 'python main.py <project_dir>'. You should run 'gpt-engineer <project_dir> <options>' from the root of the repo (notice that main.py is inside a folder called gpt_engineer).

**Comment by GsHeri** [comment]
the last part is very good to know. please make sure to include this in the docs soon (when you hopefully update them also very soon :D )
