### ISSUE TITLE
Use without API?

### ISSUE THREAD

**Issue by gitihobo** [AntonOsika/gpt-engineer#54]
Is there a way to use this without an API key?

**Comment by psirdev** [comment]
Maybe you need to implement your own GPT. It would be good to support to external API's or certain models, but would be hard to adapt.

**Comment by k0ns0l** [comment]
@gitihobo :: I see you're a fan of magic, hoping things work without the necessary spells ;)

**Comment by r7l** [comment]
People making fun of you for no reason. While i guess we won't see support for [gpt4free](https://github.com/xtekky/gpt4free) in the near future, you could try using [oobabooga](https://github.com/oobabooga/text-generation-webui) with the OpenAI extension. But it's said to not work so well.
Other then that, there is this project: https://github.com/go-skynet/LocalAI which provides a better working API replacement.

**Comment by psirdev** [comment]
How different are the other API's from OpenAI?

I think that with a series of adaptations and trying to decouple the code from this repository, we could do something interesting, I'm serious.

**Comment by gitihobo** [comment]
Awesome thank you r7l

**Comment by r7l** [comment]
@psirdev There isn't much (if anything at all) that would beat OpenAI current. 

The main issue i had when playing around with **gpt4free** was that it's basically sliding into non official APIs and those might break from one day to the next. And those APIs in the list are not made for the same goals. The results might vary greatly from one API to the other while you can mostly guess why since it's not always documented. 

I would prefer local LLMs for that matter anyways but so far the limitation was the context size. Most of the models where limited to 2k while OpenAI offers 32k. But that is about to change right now as someone developed [landmark-attention-qlora](https://github.com/eugenepentland/landmark-attention-qlora) which seems to allow you to expand the context size to whatever your hardware will take.

But even so, OpenAI with the official API will always give you better and more stable results. At least for now. The benefit in using local LLMs would be privacy and a way to not end up with a huge API bill by accident, just because your agent decided to write a new operating system from scratch.

**Comment by patillacode** [comment]
Seems like OP got an accepted answer, closing in favour of keeping the issues to a minimum.

**Comment by jjhw** [comment]
Look at this coding model -

https://huggingface.co/TheBloke/WizardCoder-15B-1.0-GPTQ

Here is a video showing how well it codes -

https://www.youtube.com/watch?v=XjsyHrmd3Xo

You will also need a model that can work out what type of classes / code to ask the coding model for in the first place.

**Comment by gitihobo** [comment]
Super interesting, will look into it and how to implement it inside gpt-engineer

**Comment by jjhw** [comment]
A system that can work out what type of classes / code to ask the coding model for in the first place, how about using this -
https://github.com/TransformerOptimus/SuperAGI
