### ISSUE TITLE
Application files are created with backticks

### ISSUE THREAD

**Issue by femibyte** [AntonOsika/gpt-engineer#545]
## Issue Template

File names created with backticks

## Expected Behavior

Application files should be created with normal names e.g. App.js

## Current Behavior

Application files are generated with backticks e.g. `App.js` on Mac.

## Failure Information (for bugs)

Application files are generated with backticks e.g. `App.js` on Mac.

### Steps to Reproduce

Ask gpt-engineer to create a React app. The resulting generated filenames are enclosed in backticks. Thus the generated application doesn't run successfully out of the box.

Please provide detailed steps for reproducing the issue.

1. Create prompt file
2. Run gpt-engineer on directory containing prompt file.
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by trentmillar** [comment]
It looks like the approach to get the filename is chasing whatever is defined and returned by openai in the response markdown. This is definitely going to be an issue since the response is never exactly as you expect. 

I have the same issue where the **md** "filename part" is this:
```
1. `main.py` (entrypoint file):
```

and when the below regex ops finish the filename is,**file):**

https://github.com/AntonOsika/gpt-engineer/blob/df5807f18411294efee6b7c9499409a977c0a2ac/gpt_engineer/chat_to_files.py#L12-L21

**Maybe changing to just find a valid filename out of the "filename part" instead chasing an ever-changing response?**

Running the example snake project just now results in these files:
![image](https://github.com/AntonOsika/gpt-engineer/assets/1146672/4d558afe-a273-44f3-a8d5-09848ae31e1f)

**Comment by trentmillar** [comment]
Maybe this is a good replacement to match a file and possibly a file w/ path if needed?

[https://regex101.com/r/1W5ZAB/1](https://regex101.com/r/1W5ZAB/1)

**Comment by femibyte** [comment]
Thanks for your suggestions. I'll take a look.

**Comment by AntonOsika** [comment]
We can improve regexes, but the most recent prompt I think already addresses this
