### ISSUE TITLE
Analysis - Give context of a project to GPT Engineer

### ISSUE THREAD

**Issue by psirdev** [AntonOsika/gpt-engineer#79]
GPT Engineer is amazing. But right now the purpose is for small projects, projects where you need little implementations or requirements.

But... What about to give a full context of a project? If ChatGPT can understand what methods and classes has some projects on GitHub or packages in npm, maybe he can have a fully understand of a project and modify parts of it.

What about limits of ChatGPT prompt? We can give some prompts in several windows to give fully understanding of what's going on. 

I can work on this if someone has the courage to develop it with me.

**Comment by clickbrain** [comment]
I agree with this. I've used the standard ChatGPT interface to interact and create applications, but I almost always have to go back to the prompt with errors that resulted from running the code. Having a way to get ChatGPT to add functionality or fix errors would be great. 

As an example, I just had ChatGPT create a Telegram Bot, but one of the libraries it uses is throwing an error when I execute main.py. When I looked it up, it looks like it is an error caused by capitalizing the word Filters. It would be great if I could start it up again and tell gptengineer, that I ran into this error and to fix it. 

In addition, I know after using an application that I will want it to add new features or make changes to functionality and beig able to have it read in or remember what it did on a project would be ideal. 

Finally, I would like to be able to tell it to provide deployment instructions. This is important, because some users of this are using it because they don't know how to code nor deploy an application to a server and in my specific case, deploy a bot in telegram, etc. I put those instructions in main and it added it as part of the specification, but did not provide any instructions.

**Comment by jebarpg** [comment]
@psirdev @clickbrain https://github.com/AntonOsika/gpt-engineer/issues/101#issuecomment-1595792433
I believe it can be done with gpt-engineer. There is a key value pair database setup for keeping track of pass conversations and code generation which can be handing in implementing this. Also[ Code GPT](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt) has this sort of feature on selected sections of code in a file.

**Comment by clickbrain** [comment]
Any idea how this can be done? 

I haven't tried this yet, but will give it a shot: Each step in steps.py will have its communication history with GPT4 stored in the logs folder, and can be rerun with scripts/rerun_edited_message_logs.py.

**Comment by leomariga** [comment]
I put some consideration of this issue in #131 . 
I'm thinking of doing a proof of concept with some ideas mentioned in this discussion.
If anyone is developing something in this direction let me know so we can work together.

**Comment by jebarpg** [comment]
> I put some consideration of this issue in #131 . 
> I'm thinking of doing a proof of concept with some ideas mentioned in this discussion.
> If anyone is developing something in this direction let me know so we can work together.

I'm currently working on a solution to this

**Comment by AntonOsika** [comment]
Solved ✅
